login_project/login/urls.py
from django.conf.urls import url
from login import views

#Template URLs

app_name = 'login'

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

login_project/login_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from login import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^login/',include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special'),
]

login_project/login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    #addition fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username

login_project/login/forms.py
from django import forms
from django.contrib.auth.models import User
from login.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

login_project/login/views.py
from django.shortcuts import render
from login.forms import UserForm,UserProfileInfoForm


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'login/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'login/registration.html',
                            {'user_form':user_form,
                             'profile_form':profile_form,
                             'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                HttpResponse("Account Not Active!")

        else:
            print("Some tried to login and failed!")
            print("username {} and password {}".format(username,password))
            return HttpResponse("Invalid login details provided!")
    else:
        return render(request,'login/login.html',{})

login_project/templates/login/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'login:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

login_project/templates/login/index.html
{% extends 'login/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>DJANGO Home</h1>
</div>

{% endblock %}

login_project/templates/login/login.html
{% extends 'login/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login!</h1>
  <form  action="{% url 'login:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username"  placeholder="Enter Username" >

    <label for="password">Password:</label>
    <input type="password" name="password" >

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

login_project/templates/login/registration.html
{% extends "login/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="POST" >
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
  </form>

  {% endif %}
</div>

{% endblock %}